package com.mutar.libav.bridge.avutil;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : ffmpeg_build/include/libavutil/intreadwrite.h:7</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("avutil") 
public class av_alias64 extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public long u64() {
		return this.io.getLongField(this, 0);
	}
	@Field(0) 
	public av_alias64 u64(long u64) {
		this.io.setLongField(this, 0, u64);
		return this;
	}
	/** C type : uint32_t[2] */
	@Array({2}) 
	@Field(1) 
	public Pointer<Integer > u32() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : uint16_t[4] */
	@Array({4}) 
	@Field(2) 
	public Pointer<Short > u16() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : uint8_t[8] */
	@Array({8}) 
	@Field(3) 
	public Pointer<Byte > u8() {
		return this.io.getPointerField(this, 3);
	}
	@Field(4) 
	public double f64() {
		return this.io.getDoubleField(this, 4);
	}
	@Field(4) 
	public av_alias64 f64(double f64) {
		this.io.setDoubleField(this, 4, f64);
		return this;
	}
	/** C type : float[2] */
	@Array({2}) 
	@Field(5) 
	public Pointer<Float > f32() {
		return this.io.getPointerField(this, 5);
	}
	public av_alias64() {
		super();
	}
	public av_alias64(Pointer pointer) {
		super(pointer);
	}
}
