package com.mutar.libav.bridge.avutil;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : ffmpeg_build/include/libavutil/intreadwrite.h:17</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("avutil") 
public class av_alias16 extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short u16() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public av_alias16 u16(short u16) {
		this.io.setShortField(this, 0, u16);
		return this;
	}
	/** C type : uint8_t[2] */
	@Array({2}) 
	@Field(1) 
	public Pointer<Byte > u8() {
		return this.io.getPointerField(this, 1);
	}
	public av_alias16() {
		super();
	}
	public av_alias16(Pointer pointer) {
		super(pointer);
	}
}
