package com.mutar.libav.bridge.avutil;
import com.mutar.libav.bridge.avutil.AvutilLibrary.AVBuffer;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : ffmpeg_build/include/libavutil/buffer.h:14</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avutil") 
public class AVBufferRef extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : AVBuffer* */
	@Field(0) 
	public Pointer<AVBuffer > buffer() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : AVBuffer* */
	@Field(0) 
	public AVBufferRef buffer(Pointer<AVBuffer > buffer) {
		this.io.setPointerField(this, 0, buffer);
		return this;
	}
	/** C type : uint8_t* */
	@Field(1) 
	public Pointer<Byte > data() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : uint8_t* */
	@Field(1) 
	public AVBufferRef data(Pointer<Byte > data) {
		this.io.setPointerField(this, 1, data);
		return this;
	}
	@Field(2) 
	public int size() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public AVBufferRef size(int size) {
		this.io.setIntField(this, 2, size);
		return this;
	}
	public AVBufferRef() {
		super();
	}
	public AVBufferRef(Pointer pointer) {
		super(pointer);
	}
}
