package com.mutar.libav.bridge.avutil;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : ffmpeg_build/include/libavutil/fifo.h:7</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avutil") 
public class AVFifoBuffer extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : uint8_t* */
	@Field(0) 
	public Pointer<Byte > buffer() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : uint8_t* */
	@Field(0) 
	public AVFifoBuffer buffer(Pointer<Byte > buffer) {
		this.io.setPointerField(this, 0, buffer);
		return this;
	}
	/** C type : uint8_t* */
	@Field(1) 
	public Pointer<Byte > rptr() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : uint8_t* */
	@Field(1) 
	public AVFifoBuffer rptr(Pointer<Byte > rptr) {
		this.io.setPointerField(this, 1, rptr);
		return this;
	}
	/** C type : uint8_t* */
	@Field(2) 
	public Pointer<Byte > wptr() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : uint8_t* */
	@Field(2) 
	public AVFifoBuffer wptr(Pointer<Byte > wptr) {
		this.io.setPointerField(this, 2, wptr);
		return this;
	}
	/** C type : uint8_t* */
	@Field(3) 
	public Pointer<Byte > end() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : uint8_t* */
	@Field(3) 
	public AVFifoBuffer end(Pointer<Byte > end) {
		this.io.setPointerField(this, 3, end);
		return this;
	}
	@Field(4) 
	public int rndx() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public AVFifoBuffer rndx(int rndx) {
		this.io.setIntField(this, 4, rndx);
		return this;
	}
	@Field(5) 
	public int wndx() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public AVFifoBuffer wndx(int wndx) {
		this.io.setIntField(this, 5, wndx);
		return this;
	}
	public AVFifoBuffer() {
		super();
	}
	public AVFifoBuffer(Pointer pointer) {
		super(pointer);
	}
}
