package com.mutar.libav.bridge.avutil;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : ffmpeg_build/include/libavutil/motion_vector.h:9</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avutil") 
public class AVMotionVector extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int source() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public AVMotionVector source(int source) {
		this.io.setIntField(this, 0, source);
		return this;
	}
	@Field(1) 
	public byte w() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public AVMotionVector w(byte w) {
		this.io.setByteField(this, 1, w);
		return this;
	}
	@Field(2) 
	public byte h() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public AVMotionVector h(byte h) {
		this.io.setByteField(this, 2, h);
		return this;
	}
	@Field(3) 
	public short src_x() {
		return this.io.getShortField(this, 3);
	}
	@Field(3) 
	public AVMotionVector src_x(short src_x) {
		this.io.setShortField(this, 3, src_x);
		return this;
	}
	@Field(4) 
	public short src_y() {
		return this.io.getShortField(this, 4);
	}
	@Field(4) 
	public AVMotionVector src_y(short src_y) {
		this.io.setShortField(this, 4, src_y);
		return this;
	}
	@Field(5) 
	public short dst_x() {
		return this.io.getShortField(this, 5);
	}
	@Field(5) 
	public AVMotionVector dst_x(short dst_x) {
		this.io.setShortField(this, 5, dst_x);
		return this;
	}
	@Field(6) 
	public short dst_y() {
		return this.io.getShortField(this, 6);
	}
	@Field(6) 
	public AVMotionVector dst_y(short dst_y) {
		this.io.setShortField(this, 6, dst_y);
		return this;
	}
	@Field(7) 
	public long flags() {
		return this.io.getLongField(this, 7);
	}
	@Field(7) 
	public AVMotionVector flags(long flags) {
		this.io.setLongField(this, 7, flags);
		return this;
	}
	public AVMotionVector() {
		super();
	}
	public AVMotionVector(Pointer pointer) {
		super(pointer);
	}
}
