package com.mutar.libav.bridge.avutil;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : ffmpeg_build/include/libavutil/replaygain.h:10</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avutil") 
public class AVReplayGain extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int track_gain() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public AVReplayGain track_gain(int track_gain) {
		this.io.setIntField(this, 0, track_gain);
		return this;
	}
	@Field(1) 
	public int track_peak() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public AVReplayGain track_peak(int track_peak) {
		this.io.setIntField(this, 1, track_peak);
		return this;
	}
	@Field(2) 
	public int album_gain() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public AVReplayGain album_gain(int album_gain) {
		this.io.setIntField(this, 2, album_gain);
		return this;
	}
	@Field(3) 
	public int album_peak() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public AVReplayGain album_peak(int album_peak) {
		this.io.setIntField(this, 3, album_peak);
		return this;
	}
	public AVReplayGain() {
		super();
	}
	public AVReplayGain(Pointer pointer) {
		super(pointer);
	}
}
