package com.mutar.libav.bridge.avutil;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : ffmpeg_build/include/libavutil/timecode.h:17</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avutil") 
public class AVTimecode extends StructObject {
	static {
		BridJ.register();
	}
	/** < timecode frame start (first base frame number) */
	@Field(0) 
	public int start() {
		return this.io.getIntField(this, 0);
	}
	/** < timecode frame start (first base frame number) */
	@Field(0) 
	public AVTimecode start(int start) {
		this.io.setIntField(this, 0, start);
		return this;
	}
	/** < flags such as drop frame, +24 hours support, ... */
	@Field(1) 
	public int flags() {
		return this.io.getIntField(this, 1);
	}
	/** < flags such as drop frame, +24 hours support, ... */
	@Field(1) 
	public AVTimecode flags(int flags) {
		this.io.setIntField(this, 1, flags);
		return this;
	}
	/**
	 * < frame rate in rational form<br>
	 * C type : AVRational
	 */
	@Field(2) 
	public AVRational rate() {
		return this.io.getNativeObjectField(this, 2);
	}
	/**
	 * < frame rate in rational form<br>
	 * C type : AVRational
	 */
	@Field(2) 
	public AVTimecode rate(AVRational rate) {
		this.io.setNativeObjectField(this, 2, rate);
		return this;
	}
	/** < frame per second; must be consistent with the rate field */
	@Field(3) 
	public int fps() {
		return this.io.getIntField(this, 3);
	}
	/** < frame per second; must be consistent with the rate field */
	@Field(3) 
	public AVTimecode fps(int fps) {
		this.io.setIntField(this, 3, fps);
		return this;
	}
	public AVTimecode() {
		super();
	}
	public AVTimecode(Pointer pointer) {
		super(pointer);
	}
}
