package com.mutar.libav.bridge.avutil;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : ffmpeg_build/include/libavutil/xtea.h:9</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avutil") 
public class AVXTEA extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : uint32_t[16] */
	@Array({16}) 
	@Field(0) 
	public Pointer<Integer > key() {
		return this.io.getPointerField(this, 0);
	}
	public AVXTEA() {
		super();
	}
	public AVXTEA(Pointer pointer) {
		super(pointer);
	}
}
