package com.mutar.libav.bridge.avutil;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * Define AV_[RW]N helper macros to simplify definitions not provided<br>
 * by per-arch headers.<br>
 * <i>native declaration : ffmpeg_build/include/libavutil/intreadwrite.h:24</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("avutil") 
public class unaligned_64 extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public long l() {
		return this.io.getLongField(this, 0);
	}
	@Field(0) 
	public unaligned_64 l(long l) {
		this.io.setLongField(this, 0, l);
		return this;
	}
	public unaligned_64() {
		super();
	}
	public unaligned_64(Pointer pointer) {
		super(pointer);
	}
}
