package com.mutar.libav.bridge.avcodec;
import com.mutar.libav.bridge.avcodec.AvcodecLibrary.AVVDPAU_Render2;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : ffmpeg_build/include/libavcodec/vdpau.h:30</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avcodec") 
public class AVVDPAUContext extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : VdpDecoder */
	@Field(0) 
	public int decoder() {
		return this.io.getIntField(this, 0);
	}
	/** C type : VdpDecoder */
	@Field(0) 
	public AVVDPAUContext decoder(int decoder) {
		this.io.setIntField(this, 0, decoder);
		return this;
	}
	/**
	 * Failed to convert value render of type VdpDecoderRender*<br>
	 * C type : VdpDecoderRender*
	 */
	/** C type : AVVDPAUPictureInfo */
	@Field(2) 
	public AVVDPAUPictureInfo info() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : AVVDPAUPictureInfo */
	@Field(2) 
	public AVVDPAUContext info(AVVDPAUPictureInfo info) {
		this.io.setNativeObjectField(this, 2, info);
		return this;
	}
	@Field(3) 
	public int bitstream_buffers_allocated() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public AVVDPAUContext bitstream_buffers_allocated(int bitstream_buffers_allocated) {
		this.io.setIntField(this, 3, bitstream_buffers_allocated);
		return this;
	}
	@Field(4) 
	public int bitstream_buffers_used() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public AVVDPAUContext bitstream_buffers_used(int bitstream_buffers_used) {
		this.io.setIntField(this, 4, bitstream_buffers_used);
		return this;
	}
	/**
	 * Failed to convert value bitstream_buffers of type VdpBitstreamBuffer*<br>
	 * C type : VdpBitstreamBuffer*
	 */
	/** C type : AVVDPAU_Render2 */
	@Field(6) 
	public Pointer<AVVDPAU_Render2 > render2() {
		return this.io.getPointerField(this, 6);
	}
	/** C type : AVVDPAU_Render2 */
	@Field(6) 
	public AVVDPAUContext render2(Pointer<AVVDPAU_Render2 > render2) {
		this.io.setPointerField(this, 6, render2);
		return this;
	}
	public AVVDPAUContext() {
		super();
	}
	public AVVDPAUContext(Pointer pointer) {
		super(pointer);
	}
}
