package com.mutar.libav.bridge.avcodec;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : ffmpeg_build/include/libavcodec/vdpau.h:5</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("avcodec") 
public abstract class AVVDPAUPictureInfo extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : VdpPictureInfoH264 (Unsupported type) */
	/** Conversion Error : VdpPictureInfoMPEG1Or2 (Unsupported type) */
	/** Conversion Error : VdpPictureInfoVC1 (Unsupported type) */
	/** Conversion Error : VdpPictureInfoMPEG4Part2 (Unsupported type) */
}
