package com.mutar.libav.bridge.avcodec;
import org.bridj.BridJ;
import org.bridj.StructObject;
import org.bridj.ann.Library;
/**
 * <i>native declaration : ffmpeg_build/include/libavcodec/vda.h:43</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("avcodec") 
public abstract class AVVDAContext extends StructObject {
	static {
		BridJ.register();
	}
	/** Conversion Error : VDADecoder (failed to convert type to Java (undefined type)) */
	/** Conversion Error : VDADecoderOutputCallback (failed to convert type to Java (undefined type)) */
	/** Conversion Error : OSType (failed to convert type to Java (undefined type)) */
}
